<?php
namespace WBWPF\widgets;

use WBF\components\widgets\WBF_Widget;
use WBWPF\Plugin;

class Filters extends WBF_Widget {
	/**
	 * Filters constructor.
	 */
	public function __construct() {
		$plugin = Plugin::get_instance_from_global();
		if(!$plugin instanceof Plugin) return;

		parent::__construct( "waboot_woo_product_filters_widget", _x("Waboot Product Filters","Widget name","waboot-woo-product-filters") );
	}

	/**
	 * @param array $args
	 * @param array $instance
	 */
	public function widget( $args, $instance ) {
		$plugin = Plugin::get_instance_from_global();
		if(!$plugin instanceof Plugin) return;

		$default = [
			'title' => '',
			'use_async' => false
		];
		$instance = wp_parse_args($instance,$default);

		if(!function_exists("is_shop")) return;

		if(is_shop() || is_product_category()){

			echo $args['before_widget']; ?>

			<h3 class="widget-title"><?php echo $instance['title']; ?></h3>

			<?php

			if($instance['use_async']){
				wbwpf_show_filters_async();
			}else{
				wbwpf_show_filters();
			}

			echo $args['after_widget'];
		}
	}

	/**
	 * @param array $new_instance
	 * @param array $old_instance
	 *
	 * @return array
	 */
	public function update( $new_instance, $old_instance ) {
		return parent::update( $new_instance, $old_instance ); // TODO: Change the autogenerated stub
	}

	/**
	 * @param array $instance
	 * @return void
	 */
	public function form( $instance ) {
		$plugin = Plugin::get_instance_from_global();
		if(!$plugin instanceof Plugin) return;

		$form_options = [
			'title' => [
				'type' => 'text',
				'label' => _x('Title','Widget title',$plugin->get_textdomain()),
				'default' => ''
			],
			'use_async' => [
				'type' => 'checkbox',
				'label' => _x("Update filters asynchronously","Widget option",$plugin->get_textdomain()),
				'default' => false
			]
		];

		$this->print_options($instance,$form_options);
	}
}